from gradeia.modules.cenarios.comparador import ComparadorDeSolucoes
from gradeia.modules.cenarios.modelo import (
    ETAPAS_VALIDAS,
    FUNDAMENTAL,
    JANELA_DE_ALTERACAO,
    MANHA,
    MEDIO,
    NOITE,
    PERIODOS_POR_ETAPA,
    TARDE,
    TURNOS_VALIDOS,
    AtribuicaoDeAula,
    AusenciaDeProfessor,
    Cenario,
    GradeBase,
    Professor,
    RestricaoDeCenario,
    SolucaoDeCenario,
    Turma,
)
from gradeia.modules.cenarios.resultado import (
    CENARIO_INVIAVEL,
    CENARIO_VIAVEL,
    ERRO_VALIDACAO,
    ResultadoDaSimulacao,
)

__all__ = [
    "ETAPAS_VALIDAS",
    "FUNDAMENTAL",
    "JANELA_DE_ALTERACAO",
    "MANHA",
    "MEDIO",
    "NOITE",
    "PERIODOS_POR_ETAPA",
    "TARDE",
    "TURNOS_VALIDOS",
    "AtribuicaoDeAula",
    "AusenciaDeProfessor",
    "Cenario",
    "GradeBase",
    "Professor",
    "RestricaoDeCenario",
    "SolucaoDeCenario",
    "Turma",
    "ComparadorDeSolucoes",
    "CENARIO_INVIAVEL",
    "CENARIO_VIAVEL",
    "ERRO_VALIDACAO",
    "ResultadoDaSimulacao",
]
